---
- hosts: all
  ignore_errors: yes
  become: yes
  vars_files:
   - ./vars/defaults.yml
  tasks:

  - name: Parcing list pkg
    package_facts:
      manager: "auto"
  - name: Show version Zabbix agent
    debug: var=ansible_facts.packages['zabbix-agent'][0].version

  - block: # ===CHECK INSTALL===
      - include: install.yml
    when: "'zabbix-agent' not in ansible_facts.packages"

  - name: Parcing list pkg
    package_facts:
      manager: "auto"

  - include: check_to_curr.yml
  
  - name: Parcing list pkg
    package_facts:
      manager: "auto"
  - name: Show version Zabbix agent
    debug: var=ansible_facts.packages['zabbix-agent'][0].version