---
- hosts: all
  ignore_errors: yes

  vars:
    deb_pack_url: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix/zabbix-agent_6.0.4-1%2Bdebian11_amd64.deb
    ver_zabb: 1:6.0.4-1+debian11
    dir_config: /etc/zabbix/zabbix_agentd.conf
    srv_ip: 127.0.228.228

  vars_files:
   - ./vars/defaults.yml
  tasks:

  - name: Parcing list pkg
    package_facts:
      manager: "auto"
  - name: Show version Zabbix agent
    debug: var=ansible_facts.packages['zabbix-agent'][0].version

  - block: # ===CHECK INSTALL===
      - name: Install if any zabbix not install
        apt: deb={{ deb_pack_url }}
    when: "'zabbix-agent' not in ansible_facts.packages"

  - name: Parcing list pkg
    package_facts:
      manager: "auto"

  - block: # ===CHECK VERSION AND INSTALL CURRENT===
      - name: Create dir
        file:
          path: "/home/{{ user }}/zabb_bak"
          state: directory
          mode: 0777
          owner: leo
          group: leo
      - name: Copy conf file
        copy:
          src: /etc/zabbix/zabbix_agentd.conf
          dest: /home/{{ user }}/zabb_bak/zabbix_agentd.conf.bak
          remote_src: yes
      - name: Del old conf
        file: path=/etc/zabbix/zabbix_agentd.conf state=absent
      - name: Install current version
        apt: deb={{ deb_pack_url }}
    when: ansible_facts.packages['zabbix-agent'][0].version != "{{ ver_zabb }}"

  - name: Parcing list pkg
    package_facts:
      manager: "auto"

  - block: #===CHANGE VALUE IN CONFIG===
      - name: Change listen port
        shell: sed -i "s/# ListenPort=/ListenPort=/g" {{ dir_config }}
      - name: Change server passive ip
        shell: sed -i "s/Server=127.0.0.1/Server={{ srv_ip }}/g" {{ dir_config }}
      - name: Change server active ip
        shell: sed -i "s/ServerActive=127.0.0.1/ServerActive={{ srv_ip }}/g" {{ dir_config }}
      - name: Change hostname
        shell: sed -i "s/Hostname=.*/Hostname=$(cat /home/leo/zabb_bak/zabbix_agentd.conf.bak | grep "Hostname=.*" | cut -d '=' -f 2)/g" {{ dir_config }}
      - name: Restarted Zabbix
        systemd:
          name: zabbix-agent.service
          state: restarted
          enabled: yes
    when: ansible_facts.packages['zabbix-agent'][0].version == "{{ ver_zabb }}"

  - name: read the config file
    shell: cat /etc/zabbix/zabbix_agentd.conf | grep "^Hostname=.*" | cut -d '=' -f 2
    register: zabb_host
    
  - block: #===CHECK NULL HOSTNAME===
    - name: a task that only happens if string exist
      shell: sed -i "s/Hostname=.*/Hostname=$(hostnamectl | grep "Static hostname:.*" | cut -d ':' -f 2 | cut -c 2-)/g" {{ dir_config }}
    - name: Restarted Zabbix
      systemd:
        name: zabbix-agent.service
        state: restarted
        enabled: yes
    when: zabb_host.stdout == ""