---
- name: Copy conf file
  copy:
    src: /etc/zabbix/zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf.bak
    remote_src: yes
    
- name: Del old conf
  file: path=/etc/zabbix/zabbix_agentd.conf state=absent