---
- name: Uncomment listen port
  shell: sed -i "s/# ListenPort=/ListenPort=/g" {{ dir_config }}

- name: Change server passive ip
  shell: sed -i "s/"^Server=.*"/Server={{ srv_ip }}/g" {{ dir_config }}

- name: Change server active ip
  shell: sed -i "s/"^ServerActive=.*"/ServerActive={{ srv_ip }}/g" {{ dir_config }}

- name: Change hostname
  shell: sed -i "s/Hostname=.*/Hostname=$(grep "^Hostname=.*" /etc/zabbix/zabbix_agentd.conf.bak | cut -d '=' -f 2)/g" {{ dir_config }}

- name: Restarted Zabbix
  systemd:
    name: zabbix-agent.service
    state: restarted
    enabled: yes

- name: Read the config file
  shell: cat /etc/zabbix/zabbix_agentd.conf | grep "^Hostname=.*" | cut -d '=' -f 2
  register: zabb_host

- block: #===CHECK NULL HOSTNAME===
  - name: Check hostname and if it empty write system name
    shell: sed -i "s/Hostname=.*/Hostname=$(hostnamectl | grep "Static hostname:.*" | cut -d ':' -f 2 | cut -c 2-)/g" {{ dir_config }}
  - name: Restarted Zabbix
    systemd:
      name: zabbix-agent.service
      state: restarted
      enabled: yes
  when: zabb_host.stdout == ""